services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - jenkins
      - gitlab
    networks:
      - internal

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
    networks:
      - internal
    volumes:
      - jenkins:/var/jenkins_home

  gitlab:
    image: gitlab/gitlab-ce:18.6.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.internal.skocev.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.internal.skocev.com:8081'
    ports:
      - '8081:8081'
      - '22:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
    shm_size: '256m'
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  jenkins:
